name: 'Canny Changelog Updater'
description: 'Update Canny changelogs'
inputs:
  changelog:  # id of input
    description: 'What has changed?'
    required: true
    default: 'Many changes'
  outputs:
    testOutput:
      description: 'Test output'
runs:
  using: 'node12'
  main: 'index.js'